language: haskell
ghc:
  - 8.0.2
sudo: false
env:
  - GHCVER=8.0.2

addons:
 apt:
   sources:
   - hvr-ghc
   packages:
   - happy
   - hlint

cache:
  directories:
  - $HOME/.stack
  - $HOME/.ghc
  - $HOME/.local/bin

# Download and unpack the stack executable
before_install:
  - export PATH=/opt/ghc/$GHCVER/bin:$PATH
  - export PATH=$HOME/.local/bin:$PATH
  - if [ -e $HOME/.local/bin ]; 
      then echo "stack already installed" && which stack && ls $HOME/.local/bin;
      else mkdir -p $HOME/.local/bin && travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C $HOME/.local/bin '*/stack';
    fi
  - echo "completed before install"

install:
  - stack update
  - stack setup
  - stack install codecov-haskell
  - stack install --dependencies-only --test --bench

script:
  - hlint . --ignore="Parse error"
  - export ROOT_DIR=$(pwd)
  - stack --no-terminal --skip-ghc-check build
  - stack --no-terminal --skip-ghc-check test
  - stack --no-terminal --skip-ghc-check bench
  - stack --no-terminal --skip-ghc-check sdist
  - export DIST_DIR=$(stack path --dist-dir)
  - export SDIST_TAR=$(find $DIST_DIR -name "*.tar.gz" | tail -1)
  - export SDIST_FOLDER=$(basename $DIST_TAR .tar.gz)
  - tar xzf $(SDIST_TAR)
  - cd $(SDIST_FOLDER) && stack init --force && stack build --test --haddock --no-haddock-deps

after_script: 
  - codecov-haskell test-$packageName --exclude-dir=test --display-report --print-response --dont-send > .tmp-report
  - bash <(curl -s https://codecov.io/bash) -f .tmp-report

notifications:
  webhooks:
  urls:
  on_success: change
  on_failure: always
  on_start: false
  
